return {
    {
        name = "midnight_zulaman_maps_to_amani",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2437,
            mapName = "Zul'Aman",
            zoneName = "Zul'Aman",
            zoneKey = "zul aman",
            subZoneName = "Zul'Aman",
            subZoneKey = "zul aman",
            mapChain = {
                { mapID = 2437, name = "Zul'Aman" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2696,
        forbidVisibleFactionIDs = { 2699, 2704 },
    },
    {
        name = "midnight_voidstorm_maps_to_singularity",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2405,
            mapName = "Leerensturm",
            zoneName = "Leerensturm",
            zoneKey = "leerensturm",
            subZoneName = "Obskurionzitadelle",
            subZoneKey = "obskurionzitadelle",
            mapChain = {
                { mapID = 2405, name = "Leerensturm" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2699,
        forbidVisibleFactionIDs = { 2696, 2704 },
    },
    {
        name = "midnight_harandar_maps_to_harati",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2413,
            mapName = "Harandar",
            zoneName = "Harandar",
            zoneKey = "harandar",
            subZoneName = "Harandar",
            subZoneKey = "harandar",
            mapChain = {
                { mapID = 2413, name = "Harandar" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2704,
        forbidVisibleFactionIDs = { 2696, 2699 },
    },
    {
        name = "silvermoon_stays_on_court_cluster",
        profile = {
            maxBars = 7,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2393,
            mapName = "Silbermond",
            zoneName = "Silbermond",
            zoneKey = "silbermond",
            subZoneName = "Der Basar",
            subZoneKey = "der basar",
            mapChain = {
                { mapID = 2393, name = "Silbermond" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2710, name = "Hof in Silbermond", isMajorFaction = true, renownLevel = 13, progressValue = 205, progressMax = 2500, progressPct = 8.2, standingID = 5, hasRepEntry = true },
            { factionID = 2711, name = "Magister", standingID = 4, progressValue = 225, progressMax = 500, progressPct = 45, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2712, name = "Blutritter", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2713, name = "Weltenwanderer", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2714, name = "Schemen der Gasse", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2710,
        requireVisibleFactionIDs = { 2711, 2712, 2713, 2714 },
        forbidVisibleFactionIDs = { 2696 },
    },
    {
        name = "dustwallow_has_no_local_rep_and_no_fallback",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 70,
            mapName = "Düstermarschen",
            zoneName = "Düstermarschen",
            zoneKey = "düstermarschen",
            subZoneName = "Bucht der Düstermarschen",
            subZoneKey = "bucht der düstermarschen",
            mapChain = {
                { mapID = 70, name = "Düstermarschen" },
                { mapID = 12, name = "Kalimdor" },
            },
            watchedFactionID = 72,
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 72, name = "Sturmwind", standingID = 8, progressValue = 999, progressMax = 1000, progressPct = 99.9, hasRepEntry = true, isExalted = true },
        },
        expectCoverage = {
            zoneHasRecord = true,
            zoneNoLocalReputation = true,
            zoneHasMapping = false,
        },
        expectVisibleCount = 0,
    },
    {
        name = "azshara_uses_bilgewater_not_hydraxians",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 76,
            mapName = "Azshara",
            zoneName = "Azshara",
            zoneKey = "azshara",
            subZoneName = "Mennarsee",
            subZoneKey = "mennarsee",
            mapChain = {
                { mapID = 76, name = "Azshara" },
                { mapID = 12, name = "Kalimdor" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1133, name = "Bilgewasserkartell", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
            { factionID = 749, name = "Hydraxianer", description = "Diese Elementarwesen leben auf den Inseln östlich von Azshara. Erzrivalen der Armeen von Ragnaros.", standingID = 5, progressValue = 3390, progressMax = 6000, progressPct = 56.5, hasRepEntry = true },
        },
        expectTopFactionID = 1133,
        forbidVisibleFactionIDs = { 749 },
    },
}
