return {
    {
        name = "midnight_zulaman_maps_to_amani",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2437,
            mapName = "Zul'Aman",
            zoneName = "Zul'Aman",
            zoneKey = "zul aman",
            subZoneName = "Zul'Aman",
            subZoneKey = "zul aman",
            mapChain = {
                { mapID = 2437, name = "Zul'Aman" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2696,
        forbidVisibleFactionIDs = { 2699, 2704 },
    },
    {
        name = "midnight_voidstorm_maps_to_singularity",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2405,
            mapName = "Leerensturm",
            zoneName = "Leerensturm",
            zoneKey = "leerensturm",
            subZoneName = "Obskurionzitadelle",
            subZoneKey = "obskurionzitadelle",
            mapChain = {
                { mapID = 2405, name = "Leerensturm" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2699,
        forbidVisibleFactionIDs = { 2696, 2704 },
    },
    {
        name = "midnight_harandar_maps_to_harati",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2413,
            mapName = "Harandar",
            zoneName = "Harandar",
            zoneKey = "harandar",
            subZoneName = "Harandar",
            subZoneKey = "harandar",
            mapChain = {
                { mapID = 2413, name = "Harandar" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
            { factionID = 2699, name = "Die Singularität", isMajorFaction = true, renownLevel = 11, progressValue = 1290, progressMax = 2500, progressPct = 51.6, standingID = 5, hasRepEntry = true },
            { factionID = 2704, name = "Hara'ti", isMajorFaction = true, renownLevel = 9, progressValue = 2450, progressMax = 2500, progressPct = 98, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2704,
        forbidVisibleFactionIDs = { 2696, 2699 },
    },
    {
        name = "silvermoon_stays_on_court_cluster",
        profile = {
            maxBars = 7,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2393,
            mapName = "Silbermond",
            zoneName = "Silbermond",
            zoneKey = "silbermond",
            subZoneName = "Der Basar",
            subZoneKey = "der basar",
            mapChain = {
                { mapID = 2393, name = "Silbermond" },
                { mapID = 2537, name = "Quel'Thalas" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2710, name = "Hof in Silbermond", isMajorFaction = true, renownLevel = 13, progressValue = 205, progressMax = 2500, progressPct = 8.2, standingID = 5, hasRepEntry = true },
            { factionID = 2711, name = "Magister", standingID = 4, progressValue = 225, progressMax = 500, progressPct = 45, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2712, name = "Blutritter", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2713, name = "Weltenwanderer", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2714, name = "Schemen der Gasse", standingID = 4, progressValue = 0, progressMax = 500, progressPct = 0, hasRepEntry = true, parentFactionID = 2710 },
            { factionID = 2696, name = "Amanistamm", isMajorFaction = true, renownLevel = 12, progressValue = 2250, progressMax = 2500, progressPct = 90, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2710,
        requireVisibleFactionIDs = { 2711, 2712, 2713, 2714 },
        forbidVisibleFactionIDs = { 2696 },
    },
    {
        name = "dustwallow_has_no_local_rep_and_no_fallback",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 70,
            mapName = "Düstermarschen",
            zoneName = "Düstermarschen",
            zoneKey = "düstermarschen",
            subZoneName = "Bucht der Düstermarschen",
            subZoneKey = "bucht der düstermarschen",
            mapChain = {
                { mapID = 70, name = "Düstermarschen" },
                { mapID = 12, name = "Kalimdor" },
            },
            watchedFactionID = 72,
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 72, name = "Sturmwind", standingID = 8, progressValue = 999, progressMax = 1000, progressPct = 99.9, hasRepEntry = true, isExalted = true },
        },
        expectCoverage = {
            zoneHasRecord = true,
            zoneNoLocalReputation = true,
            zoneHasMapping = false,
        },
        expectVisibleCount = 0,
    },
    {
        name = "azshara_uses_bilgewater_not_hydraxians",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 76,
            mapName = "Azshara",
            zoneName = "Azshara",
            zoneKey = "azshara",
            subZoneName = "Mennarsee",
            subZoneKey = "mennarsee",
            mapChain = {
                { mapID = 76, name = "Azshara" },
                { mapID = 12, name = "Kalimdor" },
            },
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1133, name = "Bilgewasserkartell", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
            { factionID = 749, name = "Hydraxianer", description = "Diese Elementarwesen leben auf den Inseln östlich von Azshara. Erzrivalen der Armeen von Ragnaros.", standingID = 5, progressValue = 3390, progressMax = 6000, progressPct = 56.5, hasRepEntry = true },
        },
        expectTopFactionID = 1133,
        forbidVisibleFactionIDs = { 749 },
    },
    {
        name = "retail_companion_visible_when_option_enabled",
        profile = {
            maxBars = 5,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 70,
            mapName = "Düstermarschen",
            zoneName = "Düstermarschen",
            zoneKey = "düstermarschen",
            subZoneName = "Bucht der Düstermarschen",
            subZoneKey = "bucht der düstermarschen",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2640, name = "Brann Bronzebart", standingID = 4, progressValue = 250, progressMax = 2500, progressPct = 10, hasRepEntry = true },
        },
        expectTopFactionID = 2640,
    },
    {
        name = "retail_companion_hidden_when_option_disabled",
        profile = {
            maxBars = 5,
            showRetailCompanions = false,
        },
        context = {
            activeFlavor = "retail",
            mapID = 70,
            mapName = "Düstermarschen",
            zoneName = "Düstermarschen",
            zoneKey = "düstermarschen",
            subZoneName = "Bucht der Düstermarschen",
            subZoneKey = "bucht der düstermarschen",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2640, name = "Brann Bronzebart", standingID = 4, progressValue = 250, progressMax = 2500, progressPct = 10, hasRepEntry = true },
        },
        expectVisibleCount = 0,
    },
    {
        name = "retail_companion_appends_beyond_maxbars",
        profile = {
            maxBars = 1,
            showRetailCompanions = true,
        },
        context = {
            activeFlavor = "retail",
            mapID = 76,
            mapName = "Azshara",
            zoneName = "Azshara",
            zoneKey = "azshara",
            subZoneName = "Mennarsee",
            subZoneKey = "mennarsee",
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1133, name = "Bilgewasserkartell", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
            { factionID = 2640, name = "Brann Bronzebart", standingID = 4, progressValue = 250, progressMax = 2500, progressPct = 10, hasRepEntry = true },
        },
        requireVisibleFactionIDs = { 2640 },
    },
    {
        name = "retail_dragonflight_loamm_prefers_loamm_niffen",
        context = {
            activeFlavor = "retail",
            mapID = 2133,
            mapName = "Zaralekhöhle",
            zoneName = "Zaralekhöhle",
            zoneKey = "zaralekhöhle",
            subZoneName = "Loamm",
            subZoneKey = "loamm",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2510, name = "Valdrakken Accord", isMajorFaction = true, renownLevel = 20, progressValue = 1800, progressMax = 2500, progressPct = 72, standingID = 5, hasRepEntry = true },
            { factionID = 2564, name = "Loamm Niffen", isMajorFaction = true, renownLevel = 16, progressValue = 1200, progressMax = 2500, progressPct = 48, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2564,
        forbidVisibleFactionIDs = { 2510 },
    },
    {
        name = "retail_dragonflight_emerald_dream_prefers_dream_wardens",
        context = {
            activeFlavor = "retail",
            mapID = 2151,
            mapName = "Smaragdgrüner Traum",
            zoneName = "Smaragdgrüner Traum",
            zoneKey = "smaragdgrüner traum",
            subZoneName = "Central Encampment",
            subZoneKey = "central encampment",
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2507, name = "Dragonscale Expedition", isMajorFaction = true, renownLevel = 18, progressValue = 900, progressMax = 2500, progressPct = 36, standingID = 5, hasRepEntry = true },
            { factionID = 2574, name = "Dream Wardens", isMajorFaction = true, renownLevel = 14, progressValue = 2100, progressMax = 2500, progressPct = 84, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2574,
        forbidVisibleFactionIDs = { 2507 },
    },
    {
        name = "retail_outland_shattrath_family_cluster",
        profile = {
            maxBars = 6,
        },
        context = {
            activeFlavor = "retail",
            mapID = 111,
            mapName = "Shattrath",
            zoneName = "Shattrath",
            zoneKey = "shattrath",
            subZoneName = "Terrasse des Lichts",
            subZoneKey = "terrasse des lichts",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 935, name = "Die Sha'tar", standingID = 7, progressValue = 4000, progressMax = 21000, progressPct = 19, hasRepEntry = true },
            { factionID = 932, name = "Die Aldor", standingID = 6, progressValue = 3000, progressMax = 12000, progressPct = 25, hasRepEntry = true },
            { factionID = 934, name = "Die Seher", standingID = 5, progressValue = 500, progressMax = 6000, progressPct = 8.3, hasRepEntry = true },
            { factionID = 1011, name = "Unteres Viertel", standingID = 6, progressValue = 1200, progressMax = 12000, progressPct = 10, hasRepEntry = true },
        },
        expectTopFactionID = 9000111,
        requireVisibleFactionIDs = { 932, 934, 1011 },
    },
    {
        name = "retail_northrend_dalaran_prefers_kirin_tor",
        context = {
            activeFlavor = "retail",
            mapID = 125,
            mapName = "Dalaran",
            zoneName = "Dalaran",
            zoneKey = "dalaran",
            subZoneName = "Die Violette Festung",
            subZoneKey = "die violette festung",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1090, name = "Kirin Tor", standingID = 7, progressValue = 12000, progressMax = 21000, progressPct = 57.1, hasRepEntry = true },
            { factionID = 1106, name = "Argentumkreuzzug", standingID = 6, progressValue = 2000, progressMax = 12000, progressPct = 16.6, hasRepEntry = true },
        },
        expectTopFactionID = 1090,
    },
    {
        name = "retail_pandaria_isle_of_thunder_prefers_shado_pan_assault_hub",
        context = {
            activeFlavor = "retail",
            mapID = 507,
            mapName = "Insel des Donners",
            zoneName = "Insel des Donners",
            zoneKey = "insel des donners",
            subZoneName = "Insel des Donnerkoenigs",
            subZoneKey = "insel des donnerkoenigs",
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1387, name = "Kirin Tor Offensive", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
            { factionID = 1388, name = "Sunreaver Onslaught", standingID = 6, progressValue = 4200, progressMax = 12000, progressPct = 35, hasRepEntry = true },
            { factionID = 1435, name = "Shado-Pan Assault", standingID = 7, progressValue = 9000, progressMax = 21000, progressPct = 42.8, hasRepEntry = true },
        },
        expectTopFactionID = 1435,
    },
    {
        name = "retail_cataclysm_deepholm_prefers_therazane",
        context = {
            activeFlavor = "retail",
            mapID = 207,
            mapName = "Tiefenheim",
            zoneName = "Tiefenheim",
            zoneKey = "tiefenheim",
            subZoneName = "Tempel der Erde",
            subZoneKey = "tempel der erde",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1171, name = "Therazane", standingID = 6, progressValue = 7500, progressMax = 12000, progressPct = 62.5, hasRepEntry = true },
            { factionID = 1173, name = "Ramkahen", standingID = 5, progressValue = 500, progressMax = 6000, progressPct = 8.3, hasRepEntry = true },
        },
        expectTopFactionID = 1171,
    },
    {
        name = "retail_cataclysm_uldum_shows_uldum_accord",
        context = {
            activeFlavor = "retail",
            mapID = 249,
            mapName = "Uldum",
            zoneName = "Uldum",
            zoneKey = "uldum",
            subZoneName = "Ramkahen",
            subZoneKey = "ramkahen",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1173, name = "Ramkahen", standingID = 6, progressValue = 9000, progressMax = 12000, progressPct = 75, hasRepEntry = true },
            { factionID = 2417, name = "Uldum Accord", standingID = 5, progressValue = 1500, progressMax = 6000, progressPct = 25, hasRepEntry = true },
        },
        expectTopFactionID = 1173,
        requireVisibleFactionIDs = { 2417 },
    },
    {
        name = "retail_draenor_frostfire_prefers_frostwolf",
        context = {
            activeFlavor = "retail",
            mapID = 525,
            mapName = "Frostfeuergrat",
            zoneName = "Frostfeuergrat",
            zoneKey = "frostfeuergrat",
            subZoneName = "Kriegsmühle",
            subZoneKey = "kriegsmühle",
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1445, name = "Frostwolforks", standingID = 6, progressValue = 9000, progressMax = 12000, progressPct = 75, hasRepEntry = true },
            { factionID = 1710, name = "Sha'tari Defense", standingID = 4, progressValue = 0, progressMax = 3000, progressPct = 0, hasRepEntry = true },
        },
        expectTopFactionID = 1445,
    },
    {
        name = "retail_legion_suramar_prefers_nightfallen",
        context = {
            activeFlavor = "retail",
            mapID = 680,
            mapName = "Suramar",
            zoneName = "Suramar",
            zoneKey = "suramar",
            subZoneName = "Shal'Aran",
            subZoneKey = "shal aran",
            playerFactionGroup = "Horde",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 1859, name = "Die Nachtsüchtigen", standingID = 7, progressValue = 14000, progressMax = 21000, progressPct = 66.6, hasRepEntry = true },
            { factionID = 1883, name = "Traumweber", standingID = 5, progressValue = 2000, progressMax = 6000, progressPct = 33.3, hasRepEntry = true },
        },
        expectTopFactionID = 1859,
    },
    {
        name = "retail_bfa_nazjatar_alliance_prefers_ankoan",
        context = {
            activeFlavor = "retail",
            mapID = 1355,
            mapName = "Nazjatar",
            zoneName = "Nazjatar",
            zoneKey = "nazjatar",
            subZoneName = "Neuheim",
            subZoneKey = "neuheim",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2373, name = "Ankoaner", standingID = 6, progressValue = 4500, progressMax = 12000, progressPct = 37.5, hasRepEntry = true },
            { factionID = 2370, name = "Die Befreiten", standingID = 6, progressValue = 4500, progressMax = 12000, progressPct = 37.5, hasRepEntry = true },
        },
        expectTopFactionID = 2373,
        forbidVisibleFactionIDs = { 2370 },
    },
    {
        name = "retail_shadowlands_oribos_prefers_broker_faction",
        context = {
            activeFlavor = "retail",
            mapID = 1525,
            mapName = "Oribos",
            zoneName = "Oribos",
            zoneKey = "oribos",
            subZoneName = "Ring der Schicksale",
            subZoneKey = "ring der schicksale",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2413, name = "Die Entfesselten", standingID = 5, progressValue = 1700, progressMax = 6000, progressPct = 28.3, hasRepEntry = true },
            { factionID = 2407, name = "Die Aufgestiegenen", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
        },
        expectTopFactionID = 2413,
    },
    {
        name = "retail_shadowlands_revendreth_shows_avowed",
        context = {
            activeFlavor = "retail",
            mapID = 1529,
            mapName = "Revendreth",
            zoneName = "Revendreth",
            zoneKey = "revendreth",
            subZoneName = "Revendreth",
            subZoneKey = "revendreth",
            mapChain = {
                { mapID = 1529, name = "Revendreth" },
                { mapID = 1543, name = "The Shadowlands" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2413, name = "Court of Harvesters", standingID = 6, progressValue = 4500, progressMax = 12000, progressPct = 37.5, hasRepEntry = true },
            { factionID = 2439, name = "The Avowed", standingID = 5, progressValue = 1800, progressMax = 6000, progressPct = 30, hasRepEntry = true },
        },
        expectTopFactionID = 2413,
        requireVisibleFactionIDs = { 2439 },
    },
    {
        name = "retail_shadowlands_ardenweald_prefers_wild_hunt",
        context = {
            activeFlavor = "retail",
            mapID = 1565,
            mapName = "Ardenwald",
            zoneName = "Ardenwald",
            zoneKey = "ardenwald",
            subZoneName = "Ardenwald",
            subZoneKey = "ardenwald",
            mapChain = {
                { mapID = 1565, name = "Ardenweald" },
                { mapID = 1543, name = "The Shadowlands" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2464, name = "Court of Night", standingID = 5, progressValue = 900, progressMax = 6000, progressPct = 15, hasRepEntry = true },
            { factionID = 2465, name = "The Wild Hunt", standingID = 6, progressValue = 6000, progressMax = 12000, progressPct = 50, hasRepEntry = true },
        },
        expectTopFactionID = 2465,
        requireVisibleFactionIDs = { 2464 },
    },
    {
        name = "retail_dragonflight_valdrakken_prefers_valdrakken_accord",
        profile = {
            maxBars = 6,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2112,
            mapName = "Valdrakken",
            zoneName = "Valdrakken",
            zoneKey = "valdrakken",
            subZoneName = "Sitz der Aspekte",
            subZoneKey = "sitz der aspekte",
            mapChain = {
                { mapID = 2112, name = "Valdrakken" },
                { mapID = 2025, name = "Thaldraszus" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2510, name = "Valdrakken Accord", isMajorFaction = true, renownLevel = 20, progressValue = 1800, progressMax = 2500, progressPct = 72, standingID = 5, hasRepEntry = true },
            { factionID = 2507, name = "Dragonscale Expedition", isMajorFaction = true, renownLevel = 18, progressValue = 900, progressMax = 2500, progressPct = 36, standingID = 5, hasRepEntry = true },
            { factionID = 2511, name = "Iskaara Tuskarr", isMajorFaction = true, renownLevel = 15, progressValue = 600, progressMax = 2500, progressPct = 24, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2510,
    },
    {
        name = "retail_dragonflight_valdrakken_shows_artisans_consortium",
        profile = {
            maxBars = 6,
        },
        context = {
            activeFlavor = "retail",
            mapID = 2112,
            mapName = "Valdrakken",
            zoneName = "Valdrakken",
            zoneKey = "valdrakken",
            subZoneName = "Sitz der Aspekte",
            subZoneKey = "sitz der aspekte",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2510, name = "Valdrakken Accord", isMajorFaction = true, renownLevel = 20, progressValue = 1800, progressMax = 2500, progressPct = 72, standingID = 5, hasRepEntry = true },
            { factionID = 2544, name = "Artisan's Consortium - Dragon Isles Branch", standingID = 5, progressValue = 1200, progressMax = 6000, progressPct = 20, hasRepEntry = true },
        },
        expectTopFactionID = 2510,
        requireVisibleFactionIDs = { 2544 },
    },
    {
        name = "retail_dragonflight_azure_span_shows_side_factions",
        context = {
            activeFlavor = "retail",
            mapID = 2024,
            mapName = "Azurblaues Gebirge",
            zoneName = "Azurblaues Gebirge",
            zoneKey = "azurblaues gebirge",
            subZoneName = "Ismara",
            subZoneKey = "ismara",
            mapChain = {
                { mapID = 2024, name = "Azure Span" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2511, name = "Iskaara Tuskarr", isMajorFaction = true, renownLevel = 15, progressValue = 600, progressMax = 2500, progressPct = 24, standingID = 5, hasRepEntry = true },
            { factionID = 2550, name = "Cobalt Assembly", standingID = 5, progressValue = 900, progressMax = 6000, progressPct = 15, hasRepEntry = true },
            { factionID = 2526, name = "Winterpelt Furbolg", standingID = 4, progressValue = 400, progressMax = 3000, progressPct = 13.3, hasRepEntry = true },
        },
        expectTopFactionID = 2511,
        requireVisibleFactionIDs = { 2550, 2526 },
    },
    {
        name = "retail_dragonflight_thaldraszus_shows_soridormi",
        context = {
            activeFlavor = "retail",
            mapID = 2025,
            mapName = "Thaldraszus",
            zoneName = "Thaldraszus",
            zoneKey = "thaldraszus",
            subZoneName = "Tyrhold",
            subZoneKey = "tyrhold",
            mapChain = {
                { mapID = 2025, name = "Thaldraszus" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2510, name = "Valdrakken Accord", isMajorFaction = true, renownLevel = 20, progressValue = 1800, progressMax = 2500, progressPct = 72, standingID = 5, hasRepEntry = true },
            { factionID = 2553, name = "Soridormi", standingID = 5, progressValue = 2400, progressMax = 6000, progressPct = 40, hasRepEntry = true },
        },
        expectTopFactionID = 2510,
        requireVisibleFactionIDs = { 2553 },
    },
    {
        name = "retail_war_within_dornogal_prefers_council",
        context = {
            activeFlavor = "retail",
            mapID = 2339,
            mapName = "Dornogal",
            zoneName = "Dornogal",
            zoneKey = "dornogal",
            subZoneName = "Dornogal",
            subZoneKey = "dornogal",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2590, name = "Council of Dornogal", isMajorFaction = true, renownLevel = 23, progressValue = 1375, progressMax = 2500, progressPct = 55, standingID = 5, hasRepEntry = true },
            { factionID = 2594, name = "The Assembly of the Deeps", isMajorFaction = true, renownLevel = 9, progressValue = 200, progressMax = 2500, progressPct = 8, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2590,
    },
    {
        name = "retail_war_within_hallowfall_shows_flames_radiance",
        context = {
            activeFlavor = "retail",
            mapID = 2215,
            mapName = "Hallowfall",
            zoneName = "Hallowfall",
            zoneKey = "hallowfall",
            subZoneName = "Mereldar",
            subZoneKey = "mereldar",
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2570, name = "The Arathi of Hallowfall", isMajorFaction = true, renownLevel = 22, progressValue = 1000, progressMax = 2500, progressPct = 40, standingID = 5, hasRepEntry = true },
            { factionID = 2688, name = "Flame's Radiance", isMajorFaction = true, renownLevel = 8, progressValue = 300, progressMax = 2500, progressPct = 12, standingID = 5, hasRepEntry = true },
        },
        expectTopFactionID = 2570,
        requireVisibleFactionIDs = { 2688 },
    },
    {
        name = "retail_war_within_karesh_prefers_trust_cluster",
        context = {
            activeFlavor = "retail",
            mapID = 2371,
            mapName = "K'aresh",
            zoneName = "K'aresh",
            zoneKey = "k'aresh",
            subZoneName = "K'aresh",
            subZoneKey = "k'aresh",
            mapChain = {
                { mapID = 2371, name = "K'aresh" },
                { mapID = 2274, name = "Khaz Algar" },
            },
            playerFactionGroup = "Alliance",
            instanceType = "none",
            isInInstance = false,
        },
        rawFactions = {
            { factionID = 2658, name = "The K'aresh Trust", isMajorFaction = true, renownLevel = 10, progressValue = 1250, progressMax = 2500, progressPct = 50, standingID = 5, hasRepEntry = true },
            { factionID = 2736, name = "Manaforge Vandals", isMajorFaction = true, renownLevel = 6, progressValue = 600, progressMax = 2500, progressPct = 24, standingID = 5, hasRepEntry = true, parentFactionID = 2658 },
        },
        expectTopFactionID = 2658,
        requireVisibleFactionIDs = { 2736 },
    },
}
